name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build dockerfiles/umi-varcal --file dockerfiles/umi-varcal/Dockerfile --tag umi-varcal:v1.0
    - name: Push Dockerhub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login --password-stdin -u "${{ secrets.DOCKER_USERNAME }}" && docker push umi-varcal:v1.0
