name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build_umi_varcal:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    - name: build and push 
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: sheenamt/umi-varcal
        path: dockerfiles/umi-varcal/
        tags: v1.0
        dockerfile: dockerfiles/umi-varcal/Dockerfile

  build_deepsnvminer:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build and push 
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: sheenamt/deepsnvminer
        path: dockerfiles/deepsnvminer/
        tags: v1.0
        dockerfile: dockerfiles/deepsnvminer/Dockerfile